name = "analytics-service"
main = "src/index.ts"
compatibility_date = "2023-04-07"
usage_model = "bundled"
node_compat = true

[env.production]
d1_databases = [
    { binding = "DATABASE", database_name = "ridetracker-analytics-production", database_id = "b853fb69-2bdb-4c20-bb1d-4c69ad077d9a" },
    { binding = "SERVICE_DATABASE", database_name = "ridetracker", database_id = "4cb96598-71ce-47f5-b556-9ef1bfca42a1" }
]

[env.production.vars]
ENVIRONMENT = "production"

[[ env.production.kv_namespaces ]]
binding = "FEATURE_FLAGS"
id = "e9e05d97db9c4e0f8fa1e3784dc4d0ad"

[env.staging]
d1_databases = [
    { binding = "DATABASE", database_name = "ridetracker-analytics-staging", database_id = "65578fe7-4473-4a84-8c0d-9dcdd189dc3d" },
    { binding = "SERVICE_DATABASE", database_name = "ridetracker-staging", database_id = "fc97d7d6-9958-4d2c-81d8-6fb6522cd862" }
]

[env.staging.vars]
ENVIRONMENT = "staging"

[[ env.staging.kv_namespaces ]]
binding = "FEATURE_FLAGS"
id = "225cf6788c7447079e5f8dc7b9f1be18"
